const mongoose = require("mongoose");

/**
 * Report model — a snapshot of a student's progress, generated weekly
 * (via the RabbitMQ + node-cron pipeline) so parents have something
 * persistent to view rather than re-computing on every dashboard visit.
 */
const reportSchema = new mongoose.Schema(
  {
    student: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    periodStart: {
      type: Date,
      required: true,
    },
    periodEnd: {
      type: Date,
      required: true,
    },
    quizzesTaken: {
      type: Number,
      default: 0,
    },
    averageScore: {
      type: Number,
      default: 0,
    },
    subjectBreakdown: [
      {
        subject: String,
        topic: String,
        accuracy: Number,
        questionsAttempted: Number,
      },
    ],
    weakTopics: [
      {
        subject: String,
        topic: String,
        accuracy: Number,
      },
    ],
    aiSummary: {
      type: String, // plain-language narrative summary for parents, generated by Groq
      default: "",
    },
  },
  { timestamps: true }
);

reportSchema.index({ student: 1, periodEnd: -1 });

module.exports = mongoose.model("Report", reportSchema);